### ISSUE TITLE
adding an all-in-one prestodb?

### ISSUE THREAD

**Issue by shawnzhu** [big-data-europe/docker-hive#10]
I have a docker image [shawnzhu/prestodb](https://hub.docker.com/r/shawnzhu/prestodb/) which we used internally to query data on HDFS via [PrestoDB](https://prestodb.io/) where the Hive is provisioned over docker compose from this repo.

@earthquakesan If you're interested in this idea, I will create a PR to the `docker-compose.yml` Or let me know if any other ways to get this feature in.  Thanks!

**Comment by earthquakesan** [comment]
Hi @shawnzhu !

PrestoDB looks interesting and this org would definitely benefit from your contribution. If you can make a pull request, that would be awesome. I am of course available to review and merge it -)

P.S. We are using [MIT license](https://github.com/big-data-europe/README) for all the docker images/compose files in big-data-europe org.

**Comment by shawnzhu** [comment]
@earthquakesan Thanks!

close since this feature is added
