### ISSUE TITLE
No space on DataNode

### ISSUE THREAD

**Issue by webfrank** [big-data-europe/docker-hive#15]
Hi,
  I deployed the compose on a 3 node swarm but I cannot put any file on HDFS because there is no space available:

```
root@9362d3d9c816:/opt# hadoop fs -df
Filesystem            Size  Used  Available  Use%
hdfs://namenode:8020     0     0          0  NaN%
```

and I got this error if trying to copy a text file:

```
root@9362d3d9c816:/opt# hadoop fs -copyFromLocal test.txt /user/hive/
18/05/29 15:41:25 WARN hdfs.DFSClient: DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /user/hive/test.txt._COPYING_ could only be replicated to 0 nodes instead of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.
```

**Comment by gmouchakis** [comment]
Hi @webfrank,
it seems that the hadoop datanodes could not connect to the namenode. This is related to https://github.com/big-data-europe/docker-hadoop/issues/21. Please check branch  https://github.com/big-data-europe/docker-hive/tree/fix-swarm-deploy and let us know if this solves your issue.
