### ISSUE TITLE
[Question] how to run this image on the Windows 10 platform 

### ISSUE THREAD

**Issue by dileeppandiya** [big-data-europe/docker-hive#21]
Hi,
This is not issue. It is a question when i am trying to run this image on the windows 10 system. 
It is giving me the error "image operating system "linux" cannot be used on this platform".
so the question is this image only works for linux OS.
Dileep

**Comment by gmouchakis** [comment]
Hi @dileeppandiya, maybe reading https://docs.docker.com/docker-for-windows/ and especially https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers could help.

However your question is unrelated to this repository so I'll close this issue.

**Comment by dileeppandiya** [comment]
It works. Thanks.
