### ISSUE TITLE
Add export of port 8020 for namenode

### ISSUE THREAD

**Issue by BekyP** [big-data-europe/docker-hive#27]
please add export for port 8020  - I needed it when I was working with kafka connect and hdfs connector. It is a one line change: 

    ports:
      - "50070:50070"
      - "8020:8020"

**Comment by orionHong** [comment]
Thanks @BekyP , I also encountered similar issue when I'm trying to connect to Hive using Presto. Publishing this port made things a lot easier.

**Comment by BekyP** [comment]
You're welcome, I'm glad it helped

**Comment by romainr** [comment]
This one could be closed it seems?
