### ISSUE TITLE
what is username and password for remote connect 10000 port

### ISSUE THREAD

**Issue by cppla** [big-data-europe/docker-hive#30]
hello，

what is username and password for remote connect 10000 port？

i can't connect by :

> {
            "HOST": "x.x.x.x",
            "PORT": 10000,
            "DATABASE": "default",
            "USER": "",
            "PASSWORD": "",
            "AUTH": "LDAP"
        }

**Comment by shveikus** [comment]
By default, any value is available, except empty.

**Comment by cppla** [comment]
thank you very much~ @shveikus
