### ISSUE TITLE
Building fails now when downloading hive tar ball

### ISSUE THREAD

**Issue by coderigo** [big-data-europe/docker-hive#7]
Seems to be due to `2.1.0` version being removed from hive URL.
Fixed if you change `ENV HIVE_VERSION 2.1.0` to `ENV HIVE_VERSION 2.1.1` in the Dockerfile. Can send a PR later. Pretty simple.

**Comment by gmouchakis** [comment]
fixed with https://github.com/big-data-europe/docker-hive/commit/e4d8779106c755faf0dedc502497b33b2570b3dd
thanks @coderigo
